[커뮤니티] 메인 UI 구현 및 기능 구현
boostcampwm-2022/iOS08_Acha pull request #108
Opened 2022-12-01 12:09 UTC by NamSeok-Bae

### 작업 내용:
![Simulator Screen Recording - iPhone 14 Pro - 2022-12-01 at 21 02 18](https://user-images.githubusercontent.com/76683388/205049186-47de176a-ea35-4d9a-bfc5-e48249bbc86b.gif)

- 커뮤니티 메인 UI 및 기능 구현
  - 커뮤니티를 키게 되면 realtime database에서 데이터를 받아와서 게시글 목록을 보여준다.

### 이번에 공들였던 부분:

- UI 작성 부분
  - compositional layout에서 size를 estimated로 주면 알아서 resizing 될 줄 알았는데 잘 안되었다.
  - 해결방법으로 cell 내부에 있는 stackView들의 크기를 가변적으로 해줘야지 estimated가 잘 작동되었다.
  - 하지만 또다른 문제점으로 그룹 내에 margin을 주는 것이 어려웠다. 이 부분에 대한 해결 방법은 아래와 같다.
    - 기존 itemInsets 또는 groupInsets 대신 section.interGroupSpacing 을 사용해서 그룹 간의 스페이싱을 줌. (하지만 이 방법은 그룹 간의 스페이싱만 줘서 사용하기가 한정적이다.)
    - ``` stackView.isLayoutMarginsRelativeArrangement = true 와 stackView.layoutMargins = UIEdgeInsets(top: 10, left: 10, bottom: 0, right: 10)``` 으로 stackView 내부에 margin을 줬다.

### 제출 전 필수 확인 사항:

- [x] 빌드가 되는 코드인가요? 
- [x] 버그가 발생하지 않는지 충분히 테스트 해봤나요?

2022-12-01 12:53 UTC, godo129 approved these changes
수고하셨습니다 🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️

2022-12-01 12:53 UTC, godo129 commented on Acha/Acha/Presentation/TabBar/Community/ViewController/CommunityMainViewController.swift
> +        cellTapEvent.accept(cell.getId())
셀 터치 어떻게 해야 될지 고민하고 있었는 데 이렇게 하면 되겠군요 감사합니다

2022-12-01 12:53 UTC, godo129 commented on Acha/Acha/Domain/UseCase/DefaultCommunityMainUseCase.swift
> +            .disposed(by: disposeBag)
도움 주셔서 해결 거의 한거 같아요 감사합니다

2022-12-01 12:53 UTC, godo129 commented on Acha/Acha/Presentation/TabBar/Community/Cell/CommunityMainCell.swift
> +        commentInfoView.addSubview(commentCountLabel)
UI 장인 ㄷ

2022-12-01 12:53 UTC, godo129 commented on Acha/Acha/Presentation/TabBar/Community/ViewController/CommunityMainViewController.swift
> +        let input = CommunityMainViewModel.Input(viewDidAppearEvent: rx.methodInvoked(#selector(viewDidAppear(_:)))
이 부분 제가 extension 으로 빼놨습니다. rx.viewDidAppear 로 하면 됩니다 !

2022-12-01 12:53 UTC, godo129 commented on Acha/Acha/Presentation/TabBar/Community/ViewModel/CommunityMainViewModel.swift
> +            .disposed(by: disposeBag)
아 이래서 저장 한다고 하셨군요 저는 계속 주기만 하는 걸 생각 했는 데 이런 식으로 dispose 2번 쓸 필요도 없고 좋네요 
제가 생각이 짧았습니다

2022-12-01 12:54 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Community/ViewController/CommunityMainViewController.swift
> +        let input = CommunityMainViewModel.Input(viewDidAppearEvent: rx.methodInvoked(#selector(viewDidAppear(_:)))
감사합니다!

2022-12-01 13:46 UTC, seungki-cho approved these changes

2022-12-03 04:47 UTC, seungki-cho approved these changes
그는 신인가..?

2022-12-03 17:26 UTC, sangyeon3 requested changes

2022-12-03 17:26 UTC, sangyeon3 commented on Acha/Acha/Presentation/TabBar/Community/Cell/CommunityMainCell.swift
> +            $0.top.leading.trailing.bottom.equalToSuperview()
## 의견
```swift
$0.edges.equalToSuperview()
```

2022-12-03 17:26 UTC, sangyeon3 commented on Acha/Acha/Presentation/TabBar/Community/Cell/CommunityMainCell.swift
> +        postTextLabel.snp.makeConstraints {
nickNameLabel은 설정 안 해줘도 되나보네여 ?? 신기하네요

2022-12-03 17:26 UTC, sangyeon3 commented on Acha/Acha/Presentation/TabBar/Community/ViewModel/CommunityMainViewModel.swift
> +    private let useCase: CommunityMainUseCase!
!인 이유가 있을까요?

2022-12-03 17:26 UTC, sangyeon3 commented on Acha/Acha/Presentation/TabBar/Community/ViewController/CommunityMainViewController.swift
> +        )
선언ㄴ 부분이랑 중복됩니다!

2022-12-03 17:26 UTC, sangyeon3 commented on Acha/Acha/Domain/UseCase/DefaultCommunityMainUseCase.swift
> +    var repository: DefaultCommunityRepository
## lv1
의존성 이슈 !! 구현체말고 프로토콜을 가지고 있어야 합니다

2022-12-03 17:26 UTC, sangyeon3 commented on Acha/Acha/Data/Repository/DefaultCommunityRepository.swift
> +    private let service: RealtimeDatabaseNetworkService
프로토콜이 업습니다

2022-12-04 14:12 UTC, NamSeok-Bae commented on Acha/Acha/Domain/UseCase/DefaultCommunityMainUseCase.swift
> +    var repository: DefaultCommunityRepository
성철님께서 만들어서 주신 레포지토리를 사용하였습니다.

성철님께서 프로토콜을 만들면 오류가 생긴다고 하더라구요? 내일 자세히 애기해볼 것 같습니다.

2022-12-04 14:15 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Community/ViewController/CommunityMainViewController.swift
> +        )
수정했습니다!

2022-12-04 14:16 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Community/ViewModel/CommunityMainViewModel.swift
> +    private let useCase: CommunityMainUseCase!
보통 init에서 초기화해주지않을때 ! 을 자주 썼었는데 이런 실수를 남겨버렸네요. 감사합니다

2022-12-04 14:17 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Community/Cell/CommunityMainCell.swift
> +            $0.top.leading.trailing.bottom.equalToSuperview()
edges가 어색했는데 이참에 써보겠습니다!

2022-12-06 04:54 UTC, closed without merging