[기록] 맵 랭킹
boostcampwm-2022/iOS08_Acha pull request #72
Opened 2022-11-23 07:34 UTC by NamSeok-Bae

## 작업 내용:
<img src="https://user-images.githubusercontent.com/76683388/203490350-accb01c1-681f-4f34-9ab3-4a05afc1ee5a.gif" width="300" height="600"/>

### RecordView 분리
- RecordView를 Main 과 Map 으로 ViewController를 분리해줌
- pageViewController 안에 Main 과 Map ViewController 넣어주고 slide를 통해 넘길 수 있도록 구현하였습니다.

### RecordMainViewController
- Input, Output 패턴 적용

### RecordMapViewController
- Input, Output 패턴 적용
- Collection View 구현
   -  Sections, items ( category, ranking, map)
   -  Category 셀 클릭 시, 해당 Category에 속하는 맵을 매칭하고, 맵의 기록들을 보여준다.
   - ranking headerView에서 dropDown button을 클릭하면 맵 이름이 메뉴 형식으로 나타나고, 클릭 시 해당 맵의 기록들을 보여준다.

## 질문:
- MapViewController에서 headerView에서의 action을 MapViewController로 바꿔주는 부분을 구현하는데 고민이 많았습니다.
현재는 headerView에서 parentViewController라고 인자를 만들어서 MapViewController에서 header View를 불러올 때 초기화해주고 있습니다. 이러한 방식이 맞는지 궁금합니다.

- CollectionView Layout 을 정의해줄 때의 방식이 main 과 map 에서 서로 다릅니다. 어느 방식이 마음에 드는지 코멘트 부탁드립니다.

## 제출 전 필수 확인 사항:

- [x] 빌드가 되는 코드인가요? 
- [x] 버그가 발생하지 않는지 충분히 테스트 해봤나요?

2022-11-23 08:16 UTC, seungki-cho commented on Acha/Acha/Domain/UseCase/DefaultRecordMapViewUseCase.swift
> +    var ref: DatabaseReference!
# 질문

```let ref = Databse.databse().reference()``` 와 차이가 무엇인지 아시나요? ( 진자 모름 )

2022-11-23 08:38 UTC, NamSeok-Bae commented on Acha/Acha/Domain/UseCase/DefaultRecordMapViewUseCase.swift
> +    var ref: DatabaseReference!
초기화 부분이 다른 것 밖에 없습니다.
init()에 가시면 ``` ref = Databse.databse().reference() ```  이렇게 돼있습니다.

2022-11-23 09:33 UTC, seungki-cho requested changes
수고하셨습니다.😂

2022-11-23 09:33 UTC, seungki-cho commented on Acha/Acha/Presentation/TabBar/Record/RecordMain/RecordMainViewModel.swift
> +}
viewController에서만 사용하는 이 메소드 왜 있죠

2022-11-23 09:33 UTC, seungki-cho commented on Acha/Acha/Presentation/TabBar/Record/RecordMap/RecordMapHeaderView.swift
> +                    self.parentViewController.appendRankingSectionAndItems(mapName: action.title)
# 질문
액션에 대한 처리를 직접 하고 계씬걸로 보입니다만..
괜찮을까요?

2022-11-23 09:33 UTC, seungki-cho commented on Acha/Acha/Presentation/TabBar/Record/RecordMap/RecordMapViewController.swift
> +            }
좋네요

2022-11-23 09:33 UTC, seungki-cho commented on Acha/Acha/Presentation/TabBar/Record/RecordMap/RecordMapViewController.swift
> +              let maps = self.viewModel.mapDataAtCategory[categoryName] else {
# 의견
```let map = self.viewModel.mapDataAtCategory[categoryName][0]```

2022-11-23 09:33 UTC, seungki-cho commented on Acha/Acha/Presentation/TabBar/Record/RecordMap/RecordMapViewController.swift
> +    func appendRankingSectionAndItems(categoryName: String? = "인천") {
# 의견
이전의 선택된 것들을 제거하고 새로 선택한 것을 추가하므로
```appendRankingSectionAndItems``` 어떠신가요..?

2022-11-23 09:33 UTC, seungki-cho commented on Acha/Acha/Presentation/TabBar/Record/RecordMap/RecordMapViewController.swift
> +    }
# 의견
현재 유저의 이벤트 발생할 때 마다  
viewController에서 viewModel을 참조해서, 원하는 것들만 가져와서 snapShot을 변경하는데 맞나요??
제 생각에는 VC이벤트 -> viewModel input -> 유저케이스 데이터변경 -> viewModel output -> VC변경 이 되어야 할 것 같아서 말씀드립니다. 어떻게 생각하시나요??

2022-11-23 09:33 UTC, seungki-cho commented on Acha/Acha/Presentation/TabBar/Record/RecordPageViewController.swift
> +    }
페이지 처음 보는데 좋은 코드같습니다. 👍

2022-11-23 09:33 UTC, seungki-cho commented on Acha/Acha/Presentation/TabBar/Record/RecordMap/RecordMapViewModel.swift
> +            .disposed(by: disposeBag)
마찬가지로 output에 bind해주지만, VC에서는 다시 ViewModel로 데이터를 옮기는게 어색하게 느껴집니다.

2022-11-23 09:37 UTC, godo129 approved these changes
수고하셨습니다.

2022-11-23 09:37 UTC, godo129 commented on Acha/Acha/Presentation/TabBar/Record/RecordMain/RecordMainViewModel.swift
> +        return mapName
이게 datasource 단에 있어야 될 것 같습니다.

2022-11-23 09:37 UTC, godo129 commented on Acha/Acha/Presentation/TabBar/Record/RecordMap/RecordMapViewModel.swift
> +    let achaCategorys = ["서울", "인천", "경기", "부산", "경북", "경남","충남", "충북", "대전","광주", "전남", "전북", "강원"]
이 부분 이렇게 배열 형식으로 있는 게 맞을 까요...
enum + rawvalue 쓰는 건 어떻게 생각하시는 지 궁금합니다.

2022-11-23 09:46 UTC, NamSeok-Bae commented on Acha/Acha/Domain/UseCase/DefaultRecordMapViewUseCase.swift
> +final class DefaultRecordMapViewUseCase {
어.. 한글이 해석이 잘 안되네요 ㅠ.ㅠ 
해당 뷰에서만 사용하는 usecase가 맞습니다.
이것을 물어보시는게 맞을까요?

2022-11-23 09:46 UTC, NamSeok-Bae commented on Acha/Acha/Domain/UseCase/DefaultRecordMapViewUseCase.swift
> +    func fetchAllData() {
네 맞습니다!

2022-11-23 09:46 UTC, NamSeok-Bae commented on Acha/Acha/Domain/UseCase/RecordMainViewUseCase.swift
> +}
레포지토리가 만들어지면 저 곳에 함수들의 원형을 두고 사용할 예정입니다.

2022-11-23 09:51 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Record/RecordMain/RecordMainViewController.swift
>  }
전역으로 선언한건 예전이 버릇이 있어서 그랬습니다. 이것은 클래스 내부에 옮기도록 하겠습니다.

typealias 말하시는 부분이 dataSource말씀하시는거 같은데 맞을까요??

2022-11-23 09:52 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Record/RecordMain/RecordMainViewController.swift
> +                self.viewModel.sectionDays = sectionDays
데이터를 다 받은 후에 section header에서 사용할 수 있어야되서 저렇게 viewModel에 따로 프로퍼티를 둬서 저장하게 해두었습니다.

혹시 잘못된 방법일까요..?

2022-11-23 09:55 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Record/RecordMain/RecordMainViewController.swift
> +    }
MainViewController와 MapViewController를 왔다갔다하다보면 snapshot 에러가 떳습니다.
저는 현재 MainViewController에서 viewDidLoadEvent로 데이터를 받아오게 되는데, 뷰컨을 왔다갔다 하다보면 데이터를 매번 받게 되고 snapshot을 비워주지않으면 snapshot이 unique하지 않다는 에러가 떠서 저렇게 했습니다.

TMI로 snapshot.deleteSection을 하게되면 해당 섹션 안에 있는 아이템이 모두 삭제됩니다.

2022-11-23 09:55 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Record/RecordMain/RecordMainViewModel.swift
> +import RxSwift
아 다 수정해야겠군요! 감사합니다

2022-11-23 09:59 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Record/RecordMain/RecordMainViewModel.swift
> +
데이터를 받아온 이후에 이벤트로 처리가 가능하다면 저렇게 안했을텐데..

데이터를 모두 받아와서 정렬하고, header View가 만들어지는 시점에 데이터를 쓸 수가 없어서 저렇게 저장을 해두었습니다.

혹시 다른 방법이 있을까요? 밑이 진행되는 흐름입니다.

dataSource 정의 -> 데이터 받기 -> 정렬
정렬 후에 dataSource header View 에서 사용...

2022-11-23 10:00 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Record/RecordMain/RecordMainViewModel.swift
> +                    self.isFethed = true
넵 맞습니다. 일단은 viewDidLoadEvent가 여러번 발생하기때문에 데이터를 유지시키도록 isFetched 를 추가해주었습니다.

이 부분을 cache로 처리할지 아니면 그냥 계속 받아와서 새로 snapshot을 만들어줄지 향후 프로젝트 진행방향에 정해질 것 같습니다.

2022-11-23 10:01 UTC, seungki-cho commented on Acha/Acha/Domain/UseCase/DefaultRecordMapViewUseCase.swift
> +final class DefaultRecordMapViewUseCase {
죄송함ㄷ니다 제가 말을 잘 못해서ㅠ
넵 맞습니다 
유즈케이스가 해당 뷰에서만 사용하도록 설계해도 되는지 몰라서 옂줘봤습니다.

2022-11-23 10:02 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Record/RecordMain/RecordMainViewModel.swift
> +}
... 변수를 잘 정의하고 사용한다면 그냥 가져와서 쓸 수 있을 것 같은데 풀리퀘의 범위가 커지면서 고치질 않았군요.. 리팩토링 하겠습니다.

2022-11-23 10:03 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Record/RecordMap/RecordMapHeaderView.swift
> +                    self.parentViewController.appendRankingSectionAndItems(mapName: action.title)
자세히 말해주실 수 있을까요??

2022-11-23 10:03 UTC, seungki-cho commented on Acha/Acha/Presentation/TabBar/Record/RecordMain/RecordMainViewController.swift
>  }
typealias는 collection view 아래에서 사용할때  스냅샷 등에서
<section, item>와 같은 형식으로 사용했었습니다만 이제보니 남석님의 코드가 더 좋아보이네요

2022-11-23 10:05 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Record/RecordMap/RecordMapViewController.swift
> +              let maps = self.viewModel.mapDataAtCategory[categoryName] else {
저도 처음에 그렇게 했는데 ```self.viewModel.mapDataAtCategory[categoryName]``` 이 부분이 옵셔널이라서 처리를 한번 해줘야 됩니다. 그리고 [0] 으로 빼내는 부분은 옵셔널이 아니라서 저렇게 해주었습니다.

2022-11-23 10:05 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Record/RecordMap/RecordMapViewController.swift
> +    func appendRankingSectionAndItems(categoryName: String? = "인천") {
좋습니다 :)

2022-11-23 10:08 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Record/RecordMap/RecordMapViewController.swift
> +    }
저도 그렇게 생각합니다.. 함수를 실행시키고 난 후에 rx 연결이 아직 많이 미숙하다고 생각합니다. 공부하겠습니다.

2022-11-23 10:08 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Record/RecordMap/RecordMapViewModel.swift
> +            .disposed(by: disposeBag)
시정하겠슴다!

2022-11-23 10:09 UTC, NamSeok-Bae commented on Acha/Acha/Domain/UseCase/DefaultRecordMainViewUseCase.swift
> +    var weekDistances = PublishSubject<[RecordViewChartData]>()
레포지토리가 만들어지면 그쪽으로 옮길 예정입니다!

2022-11-23 10:10 UTC, NamSeok-Bae commented on Acha/Acha/Domain/UseCase/DefaultRecordMainViewUseCase.swift
> +}
이 부분들도 firebaseManager? Service가 만들어지면 레포지토리도 그에 따라 만들어서 할당할 계획이라 현재 유즈 케이스에 있는 부분들이 레포지토리로 이관되야하는게 맞습니다.

2022-11-23 10:12 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Record/RecordMap/RecordMapViewModel.swift
> +    let useCase: DefaultRecordMapViewUseCase!
! 가 있으면, 할당되지 않았을 때 에러가 떠서 습관적으로 사용한 것 같습니다.

! 없어도 같은 결과를 내긴합니다.

2022-11-26 09:27 UTC, sangyeon3 reviewed
## 의견

제네릭 사용해서 디코딩까지 한 결과를 보내주도록 realtime database network service를 만들면 좋을 것 같아서 만들어봤습니다 ... ........ 

```swift
//
//  RealtimeDatabaseNetworkService.swift
//  firebaseTest
//
//  Created by  sangyeon on 2022/11/26.
//

import Firebase
import RxSwift

enum NetworkError: Error {
    case dataError
    case decodeError
}

protocol RealtimeDatabaseNetworkService {
    func fetch<T: Decodable>(path: String) -> Single<T>
}

final class DefaultRealtimeDatabaseNetworkService: RealtimeDatabaseNetworkService {
    private let databaseReference: DatabaseReference = Database.database().reference()
    
    private func childReference(path: String) -> DatabaseReference {
        return databaseReference.child(path)
    }
    
    func fetch<T: Decodable>(path: String) -> Single<T> {
        return Single.create { [weak self] single in
            guard let self else { return Disposables.create() }
            let childReference = self.childReference(path: path)
            childReference.observeSingleEvent(of: .value, with: { snapshot in
                guard let snapData = snapshot.value as? [Any],
                      let jsonData = try? JSONSerialization.data(withJSONObject: snapData) else {
                    single(.failure(NetworkError.dataError))
                    return
                }
                guard let data = try? JSONDecoder().decode(T.self, from: jsonData) else {
                    single(.failure(NetworkError.decodeError))
                    return
                }
                single(.success(data))
            })
            return Disposables.create()
        }
    }
}
```

```swift
// 레포지토리에서 이런 식으로 사용하면 됩니다!
    private func fetchData() {
        realtimeDatabaseService.fetch(path: "list")
            .subscribe(onSuccess: { (todos: [String]) in
                print("success: \(todos)")
            }, onFailure: { error in
                print("failure: \(error)")
            })
            .disposed(by: disposeBag)
    }
```

2022-11-26 09:59 UTC, sangyeon3 commented on Acha/Acha/Domain/Entity/Map.swift
> +    case mapID = "mapId"
records와 코딩키 사이에 줄바꿈 한 번만 ... 부탁드립니다 😅

2022-11-26 09:59 UTC, sangyeon3 commented on Acha/Acha/Domain/Entity/RecordViewRecord.swift
> +    var id: Int
별 건 아니지만 이왕이면 id가 첫번째 프로퍼티이면 더 좋을 것 같습니다!

2022-11-26 09:59 UTC, sangyeon3 commented on Acha/Acha/Domain/UseCase/DefaultRecordMainViewUseCase.swift
> +    private let ref: DatabaseReference!
파이어베이스 서비스 만들게 되면서 안 쓰는 것들은 지워주세용
```swift
import Firebase
private let ref: DatabaseReference!
```

2022-11-26 09:59 UTC, sangyeon3 commented on Acha/Acha/Presentation/TabBar/Coordinator/RecordCoordinator.swift
> +        let mapViewModel = RecordMapViewModel(useCase: mapUseCase)
main과 map 두 화면에 동일한 레포지토리 인스턴스 쓰는 것 가능할까요 ?? 
뷰가 다르니까 레포지토리 인스턴스를 각각 써야하는지, 아니면 하나로 같이 써도 될 지 잘 모르겠네요

2022-11-26 09:59 UTC, sangyeon3 commented on Acha/Acha/Domain/UseCase/DefaultRecordMainViewUseCase.swift
> +    }
usecase가 init 될 때 한 번 mapData 가져와서 사용하고 계시는데, 
그러면 처음에 RecordCoordinator에서 showRecordPageViewController() 메소드 호출할 때 한 번만 데이터를 가져오고 갱신되지 않아서
앱을 켠 이후에 실제 데이터베이스의 데이터가 달라지더라도 기록 화면에는 새로운 데이터가 반영되지 않습니다

loadMapData()와 loadRecordData()의 시점을 RecordPageViewController가 viewWillAppear 될 때로 바꿔줘야 할 것 같습니다!

2022-11-26 09:59 UTC, sangyeon3 commented on Acha/Acha/Domain/UseCase/DefaultRecordMainViewUseCase.swift
> +    var recordsAtDate = PublishSubject<[String: [RecordViewRecord]]>()
firebase에서 가져온 데이터들을 데이터 불러오는 함수들의 리턴값으로 안 주고 따로 프로퍼티로 빼주신 이유가 있을까요??
저라면 Single 같은 타입의 리턴값으로 주고 그걸 구독해서 사용할 것 같은데 순수한 궁금증에 여쭈어봅니다!

2022-11-26 13:53 UTC, sangyeon3 commented on Acha/Acha/Domain/UseCase/DefaultRecordMapViewUseCase.swift
> +    }
MainView에서랑 마찬가지로 
fetchMapDataAtMapName()랑 fetchMapDataAtCategory() 둘 다 loadMapData()를 호출해서 로직이 2번 돌 것 같은데 확인부탁드립니다~

2022-11-26 13:53 UTC, sangyeon3 commented on Acha/Acha/Domain/UseCase/DefaultRecordMapViewUseCase.swift
> +    }
fetchMapDataAtCategory()의 리턴값이 딕셔너리니까 바로 Category 키로 접근해도 될 것 같은데 따로 만들어주신 이유가 있나요?
지금은 해당 함수를 호출할 때마다 mapDataAtCategory를 만들어낼 것 같은 느낌입니다 (확인해주신다면 매우 감사하빈다)

2022-11-26 13:53 UTC, sangyeon3 commented on Acha/Acha/Domain/UseCase/DefaultRecordMapViewUseCase.swift
> +    }
## 의견
mapName을 key값으로 하는 딕셔너리를 만들지 않아도 map 리스트들을 가져와서 저장해두고 map들을 순회하며 $0.name == mapName인 map들을 가져와도 될 것 같아요
(개인적인 의견으로 지금은 중복된 정보를 다른 구성으로 여러번 저장하여 불필요하게 메모리를 쓰고 있다는 생각이 듭니다)

2022-11-26 13:53 UTC, sangyeon3 commented on Acha/Acha/Domain/UseCase/DefaultRecordMapViewUseCase.swift
> +    }
정확히 뭐하는 함수인지 설명해주실 수 있나요??

2022-11-26 13:53 UTC, sangyeon3 commented on Acha/Acha/Domain/UseCase/DefaultRecordMapViewUseCase.swift
> +    }
## 의견
```swift
func getRecordsAtindexes(indexes: [Int]) -> Observable<[RecordViewRecord]> {
    return self.fetchRecordDataAtIndex()
                .map { recordAtIndex in
                    var records = recordAtIndex
                        .filter { indexes.contains($0.key) }
                        .map { $0.value }
                    return records.sort { return $0.time < $1.time }
                 }
}
```
근데 여기서의 index는 뭘 의미하나요?? 
그리고 getRecordsAtindexes 메소드가 같은 map의 기록들을 정렬해줄 때 사용하는 것 같은데 맞나요

2022-11-26 13:53 UTC, sangyeon3 commented on Acha/Acha/Domain/UseCase/DefaultRecordMapViewUseCase.swift
> +                    }.disposed(by: self.disposeBag)
왜 0번째 map에 대한 정보만 가져오는건가요 ?? 한 카테고리에 여러 맵이 들어있는게 아닌가요 ??

그리고 어떤 map의 완주한 기록들을 가져올 때, 모든 records 가져와서 (ex. fetchAllRecords())-> map의 records에 저장된 id의 record만 뽑아내면 (ex. fetchRecords(ids: [Int])) 될 것 같은데 너무 여러 메소드로 쪼개져있는 것 같습니다.. 가독성이 살짝 아쉽네요

2022-11-26 13:53 UTC, sangyeon3 commented on Acha/Acha/Domain/UseCase/DefaultRecordMapViewUseCase.swift
> +}
getMapNameAndRecordsAtCategory()랑 getMapNameAndRecordsAtMapName()는 왜 같은 mapNameAndReocrds에 값을 전달해주는걸까요 ... 둘의 차이점이 뭔지요?? 로직이 거의 같네요

2022-11-26 13:53 UTC, sangyeon3 commented on Acha/Acha/Presentation/TabBar/Record/RecordMain/RecordMainCell.swift
> +    }
bindEvent는 어떻게 사용되나요 ??

2022-11-26 13:53 UTC, sangyeon3 commented on Acha/Acha/Presentation/TabBar/Record/RecordMain/RecordMainChartCell.swift
> +        }
예외 처리 굿

2022-11-26 13:53 UTC, sangyeon3 commented on Acha/Acha/Presentation/TabBar/Record/RecordMain/RecordMainViewController.swift
> +            }).disposed(by: disposeBag)
여기서의 headerRecord가 날마다의 distance랑 칼로리 기록 말하는 거 맞나요 ?? 
헤더레코드가 복수여야 할 것 같은데 단수인 것 같아서 궁금해서 여쭤봅니다

2022-11-26 13:53 UTC, sangyeon3 commented on Acha/Acha/Presentation/TabBar/Record/RecordMain/RecordMainViewController.swift
> +    var cell = RecordMainCell()
cell이랑 headerView는 어떻게 쓰이는 건가요 (정말 모르겠습니다)

2022-11-26 13:53 UTC, sangyeon3 commented on Acha/Acha/Presentation/TabBar/Record/RecordMain/RecordMainViewController.swift
> +                self.cell = cell
??

2022-11-26 13:53 UTC, sangyeon3 commented on Acha/Acha/Presentation/TabBar/Record/RecordMain/RecordMainViewController.swift
> +                    }).disposed(by: self.disposeBag)
로직 설명 부탁듭립니다. .정말 모르겠어요

2022-11-26 13:53 UTC, sangyeon3 commented on Acha/Acha/Presentation/TabBar/Record/RecordMain/RecordMainViewController.swift
> +                cell.bind(recordViewRecord: recordViewRecord)
## 의견

`cell.bind(mapID: mapID, record: record)` 하나로 합치는 건 어떠신지요

2022-11-26 16:26 UTC, seungki-cho requested changes
안녕하세요 수고가 많으십니다. 
1차적으로 봤는데 상당히 좋아진 것 같습니다.
어제부터 봤지만 다 못 봤지만 일단 올리고 더 보겠습니다. . . 리뷰에 대한 리뷰도 오래 걸리니까요

2022-11-26 17:16 UTC, sangyeon3 reviewed
로직 고생많으셨겠네요 수고하셨습니다!
저도 아직 다 못 봐서 내일 마저 리뷰 드리겠습니다

2022-11-27 05:40 UTC, NamSeok-Bae commented on Acha/Acha/Network/DefaultRealtimeDatabaseNetworkService.swift
> +                        observer.onCompleted()
그렇군요! 감사합니다

2022-11-27 05:41 UTC, NamSeok-Bae commented on Acha/Acha/Domain/Entity/Map.swift
> +    case mapID = "mapId"
저거.. 상연님 or 승기님이 보내주신 코드를 복붙해서 썼는데.......... 수정하겠습니다!

2022-11-27 05:41 UTC, NamSeok-Bae commented on Acha/Acha/Domain/Entity/RecordViewRecord.swift
> +    var id: Int
넵!

2022-11-27 05:43 UTC, NamSeok-Bae commented on Acha/Acha/Domain/UseCase/DefaultRecordMainViewUseCase.swift
> +    private let ref: DatabaseReference!
앗! 감사합니다.

2022-11-27 05:49 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Coordinator/RecordCoordinator.swift
> +        let mapViewModel = RecordMapViewModel(useCase: mapUseCase)
아 이부분에서 동일하게 처리했어야했는데 제가 지나친 부분이군요.

동일한 레포지토리 인스턴스를 사용해도됩니다!

2022-11-27 05:58 UTC, NamSeok-Bae commented on Acha/Acha/Domain/UseCase/DefaultRecordMainViewUseCase.swift
> +    }
저도 이 부분에 대해서 고민하고 있었습니다. tabBar Item으로 클릭 됐을 때 로드를 해주는게 나을지를 생각하고 있었는데, 상연님이 말씀해주신 방법이랑 결국은 똑같네요!

그러면 또 다른 질문이 생기는데, pageViewController와 다른 useCase간의 관계를 어떻게 해야할까요?

2022-11-27 05:58 UTC, NamSeok-Bae commented on Acha/Acha/Domain/UseCase/DefaultRecordMainViewUseCase.swift
> +        }
꿀팁 감사합니다.

2022-11-27 06:01 UTC, NamSeok-Bae commented on Acha/Acha/Domain/UseCase/DefaultRecordMainViewUseCase.swift
> +    func fetchTotalDataAtDay() -> Observable<[String: DayTotalRecord]> {
수정하겠습니다

2022-11-27 06:02 UTC, NamSeok-Bae commented on Acha/Acha/Domain/UseCase/DefaultRecordMainViewUseCase.swift
> +    func fetchTotalDataAtDay() -> Observable<[String: DayTotalRecord]> {
감사합니다 :)

2022-11-27 06:03 UTC, NamSeok-Bae commented on Acha/Acha/Domain/UseCase/DefaultRecordMainViewUseCase.swift
> +    func getmapAtRecordId(mapId: Int) {
어라 저게 왜저러지 하하

2022-11-27 06:05 UTC, NamSeok-Bae commented on Acha/Acha/Domain/UseCase/DefaultRecordMapViewUseCase.swift
> +    }
넵 맞습니다.
그리고 recordId로 record 를 찾는 경우가 있는데 그때를 대비해서 O(1)에 매칭시키게 할려고 저렇게 했습니다.

2022-11-27 06:06 UTC, NamSeok-Bae commented on Acha/Acha/Domain/UseCase/DefaultRecordMapViewUseCase.swift
> +    }
이 부분에 대해서 코드를 짤 때, 매번 기록이 갱신되면 달라져야하기때문에 저렇게 해두었습니다.

저 부분은 따로 캐시 처리를 해야하는 부분이라고 생각이 됩니다.

2022-11-27 06:08 UTC, NamSeok-Bae commented on Acha/Acha/Domain/UseCase/DefaultRecordMapViewUseCase.swift
> +    }
맵 랭킹 확인하는 부분은 볼 때마다 실시간으로 정보를 가져와야한다고 생각이 되어 저렇게 해주었습니다.

2022-11-27 06:11 UTC, NamSeok-Bae commented on Acha/Acha/Domain/UseCase/DefaultRecordMapViewUseCase.swift
> +    }
지금 생각해보니 맵 데이터는 정적이니깐 상관없군요?!?!?!?!?

다 고치겠습니다.

2022-11-27 06:12 UTC, NamSeok-Bae commented on Acha/Acha/Domain/UseCase/DefaultRecordMapViewUseCase.swift
> +    }
맵 랭킹 화면에서 섹션 헤더로 버튼을 하나 가집니다.
해당 버튼을 눌렀을 때, 아래에는 해당 카테고리에 속한 맵들을 호출해줘야합니다.

근데 섹션 헤더에는 맵 네임 밖에 정보를 가진게 없기 때문에, 맵 네임을 가지고 카테고리를 찾고, 찾은 카테고리로 속한 맵들을 찾는 과정입니다.

2022-11-27 06:14 UTC, NamSeok-Bae commented on Acha/Acha/Domain/UseCase/DefaultRecordMapViewUseCase.swift
> +    }
recordAtIndex 는 Map 구조체 안에 있는 record의 인덱스를 나타냅니다.

맵의 레코드 인덱스를 토대로 레코드를 찾는 함수를 getRecordsAtindexes 라고 명명하였습니다.

2022-11-27 06:21 UTC, NamSeok-Bae commented on Acha/Acha/Domain/UseCase/DefaultRecordMapViewUseCase.swift
> +                    }.disposed(by: self.disposeBag)
'왜 0번째 map에 대한 정보만 가져오는건가요 ?? 한 카테고리에 여러 맵이 들어있는게 아닌가요 ??'
카테고리를 눌렀을 때, 화면에 떠야하는 맵의 랭킹이 하나여야 하기때문에 가장 첫번째 맵의 데이터를 가져온 것입니다.

'그리고 어떤 map의 완주한 기록들을 가져올 때, 모든 records 가져와서 (ex. fetchAllRecords())-> map의 records에 저장된 id의 record만 뽑아내면 (ex. fetchRecords(ids: [Int])) 될 것 같은데 너무 여러 메소드로 쪼개져있는 것 같습니다.. 가독성이 살짝 아쉽네요'
상연님의 말씀이 맞네요. 처음에 viewModel에 값을 저장해두고 썼던 시절의 로직을 그대로 옮기다보니 이런 소요가 발생한 것 같습니다. 가독성 좋게 수정하겠습니다.

2022-11-27 06:23 UTC, NamSeok-Bae commented on Acha/Acha/Domain/UseCase/DefaultRecordMapViewUseCase.swift
> +}
맨 위 상단에 있는 카테고리 섹션에서는 눌렀을 때 가질 수 있는 정보가 카테고리 이름 밖에 없습니다.

그리고 섹션 헤더에서 가질 수 있는 정보는 맵 이름 밖에 없습니다.

이 두 차이때문에 데이터를 가져오는 과정에서 로직이 살짝 다르고, 가져온 결과를 토대로 배분하는 과정은 동일합니다.

2022-11-27 06:25 UTC, sangyeon3 requested changes

2022-11-27 06:25 UTC, sangyeon3 commented on Acha/Acha/Presentation/TabBar/Record/RecordPageViewController.swift
> +
뷰컨도 init에서 초기화해주는게 어떠신가요

2022-11-27 06:25 UTC, sangyeon3 commented on Acha/Acha/Presentation/TabBar/Record/RecordPageViewController.swift
> +    }
줄바꿈이랑 white space 수정 부탁드립니다

2022-11-27 06:28 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Record/RecordMain/RecordMainCell.swift
> +    }
cell 이 생성되고 정의되는 과정에서 맵과 레코드의 데이터가 필요합니다.
그래서 cell 이 생성되고난 후에 cell.bind()를 통해 이벤트를 발행하고 viewController에서 구독 및 발행해서 뷰모델에 연결해주고, 다시 뷰컨에서 구독해서 cell에 정보를 넣는 형식으로 해주었습니다.

지금 다시보니 함수 없이 그냥 바로 cell.bindEvnet.accept 해줘도 되겠군요.

2022-11-27 06:30 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Record/RecordMain/RecordMainViewController.swift
> +            }).disposed(by: disposeBag)
headerRecord 안에는 날짜, 칼로리, 거리가 저장되어있는데, 각 섹션과 1:1 관계이기 때문에 단수로 명명하였습니다.

2022-11-27 06:32 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Record/RecordMain/RecordMainViewController.swift
> +    var cell = RecordMainCell()
초기에는 headerView 와 Cell에서 viewController를 변수로 가지고 있었습니다.

승기님과 대화를 통해 이러면 양방향이 되는게 아니냐? ViewController에서 접근가능하게 되지않느냐? 라는 결론이 나오게되어 저렇게 해주었습니다.

각 headerView 와 cell에 있는 rxswift 변수들을 구독하기위해서 선언해주었습니다.

2022-11-27 06:33 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Record/RecordMain/RecordMainViewController.swift
> +                    }).disposed(by: self.disposeBag)
cell 에 있는 bindEvenet를 구독합니다.

그리고 viewController에 있는 cellBindEvent를 발행합니다.

2022-11-27 06:34 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Record/RecordMain/RecordMainViewController.swift
> +                cell.bind(recordViewRecord: recordViewRecord)
좋습니다!

2022-11-27 06:36 UTC, NamSeok-Bae commented on Acha/Acha/Data/Repository/DefaultRecordRepository.swift
> +    private let realtimeDatabaseNetworkService: RealtimeDatabaseNetworkService
아 프로토콜에 제가 까먹고 안넣었습니다. 찾아주셔서 감사합니다.

2022-11-27 06:40 UTC, NamSeok-Bae commented on Acha/Acha/Domain/UseCase/DefaultRecordMainViewUseCase.swift
> +                totalDataAtDay[$0.createdAt]?.calorie += $0.calorie
딕셔너리의 경우에 저런 식으로 없다는 것이 좀 더 보기 편하다고 생각이 되어 저렇게 해주었습니다.

혹시 이 부분도 다른 부분과 같이 if let 으로 통일하는게 좋을까요?

2022-11-27 06:40 UTC, NamSeok-Bae commented on Acha/Acha/Domain/UseCase/DefaultRecordMainViewUseCase.swift
> +    }
깃 풀해서 감사히 잘 쓰겠습니다.

2022-11-27 06:41 UTC, NamSeok-Bae commented on Acha/Acha/Domain/UseCase/DefaultRecordMainViewUseCase.swift
> +                    if let totalData = $0[dayString] {
승기님 파라미터 명시해주는거 별로 안좋아하셨던거 아니었나요...? 그 후로 왠만하면 안해주고 썼었는데

2022-11-27 06:42 UTC, NamSeok-Bae commented on Acha/Acha/Domain/UseCase/DefaultRecordMapViewUseCase.swift
> +                }
와ㅏㅏㅏ

2022-11-27 06:43 UTC, NamSeok-Bae commented on Acha/Acha/Domain/UseCase/DefaultRecordMapViewUseCase.swift
> +                }
좋은 로직 감사합니다.

2022-11-27 06:46 UTC, NamSeok-Bae commented on Acha/Acha/Domain/UseCase/DefaultRecordMainViewUseCase.swift
> +    var weekDatas = PublishSubject<[RecordViewChartData]>()
쥐엔장

2022-11-27 06:48 UTC, NamSeok-Bae commented on Acha/Acha/Domain/UseCase/DefaultRecordMainViewUseCase.swift
> +    private let repository: RecordRepository
다른 분들 코드에서
VC에서 그냥 viewModel 처럼하고
viewModel 에서도 useCase 라고 명명해서 쓰길래 따라했었는데 혹시 이유가 있을까요??

2022-11-27 06:48 UTC, NamSeok-Bae commented on Acha/Acha/Domain/UseCase/DefaultRecordMainViewUseCase.swift
> +        }
감사합니다!

2022-11-27 06:49 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Record/RecordMain/RecordMainChartCell.swift
> +
넹~

2022-11-27 06:52 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Record/RecordMap/RecordMapCategoryCell.swift
> +    }
get set 을 잘 써서 미숙했었는데 감사합니다.

2022-11-27 06:54 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Record/RecordMap/RecordMapCategoryCell.swift
> +    }
label text에 대해서 하는건데 따로 변수를 두고 해야하는 이익이 있을까요?

2022-11-27 06:55 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Record/RecordMap/RecordMapViewController.swift
> +}
저녁이라 그른가...

교실 안에 넣어둘게요!

2022-11-27 06:56 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Record/RecordMain/RecordMainViewController.swift
> +                    }).disposed(by: self.disposeBag)
명시적으로 바꾸겠습니다.

2022-11-27 06:57 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Record/RecordMain/RecordMainViewController.swift
> +                header.bind(day: section.title)
오오? 천잰데요?

2022-11-27 07:02 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Record/RecordMain/RecordMainViewController.swift
> +        let previousSections = snapshot.sectionIdentifiers.filter { $0 != .chart }
그게 안됩니다. 
$0 == .record 를 하게 되면 $0 == .record() 이런 식으로 안에 인자 넣으라고 합니다.

2022-11-27 07:02 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Record/RecordMain/RecordMainViewModel.swift
> +        self.ref = Database.database().reference()
삭제하였습니다!

2022-11-27 07:03 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Record/RecordMain/RecordMainViewModel.swift
> +        input.viewDidLoadEvent
이름이 viewDidLoadEvent이지 viewDidAppear에 대한 methodInvoke를 넘겨주고있습니다. 이 부분은 승기님의 코드를 참고해서 했었는데 리네임 하는게 좋을까요?

2022-11-27 07:03 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Record/RecordMain/RecordMainViewModel.swift
> +                self.useCase.getmapAtRecordId(mapId: mapId)
수정하였습니다

2022-11-27 07:04 UTC, NamSeok-Bae commented on Acha/Acha/Domain/UseCase/DefaultRecordMapViewUseCase.swift
> +                        self.mapNameAndReocrds.onNext((mapName, records))
감사합니다.

2022-11-27 07:05 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Record/RecordMap/RecordMapHeaderView.swift
> +    }
감사합니다.

2022-11-27 07:09 UTC, NamSeok-Bae commented on Acha/Acha/Domain/UseCase/DefaultRecordMapViewUseCase.swift
> +    }
혹시 이유가 있을까요??

2022-11-27 07:11 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Record/RecordMap/RecordMapViewController.swift
> +            }
넵 맞습니다. 이 부분은 성철님께서 imageAsset을 직접 추가하신다고해서 추후에 넣기로 했었습니다.

2022-11-27 07:15 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Record/RecordPageViewController.swift
> +
좋습니다~

2022-11-27 07:16 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Record/RecordPageViewController.swift
> +    }
수정하였습니다.

2022-11-27 07:17 UTC, NamSeok-Bae commented on Acha/Acha/Network/DefaultRealtimeDatabaseNetworkService.swift
> +        return childReference
좋습니다!

2022-11-28 02:31 UTC, seungki-cho requested changes

2022-11-28 02:31 UTC, seungki-cho commented on Acha/Acha/Domain/UseCase/DefaultRecordMainViewUseCase.swift
> +    private let repository: RecordRepository
init에서 말씀드리리려 했었던건데 잘못 달았네요

2022-11-28 02:31 UTC, seungki-cho commented on Acha/Acha/Domain/UseCase/DefaultRecordMainViewUseCase.swift
> +    init(repository: RecordRepository) {
여긴왜 안달아주세요ㅠ

2022-11-28 02:31 UTC, seungki-cho commented on Acha/Acha/Domain/UseCase/DefaultRecordMainViewUseCase.swift
> +                totalDataAtDay[$0.createdAt]?.calorie += $0.calorie
그저 질문이었습니다. 
저는 if let을 선호해서요 ㅎㅎ

2022-11-28 02:31 UTC, seungki-cho commented on Acha/Acha/Domain/UseCase/DefaultRecordMainViewUseCase.swift
> +                    if let totalData = $0[dayString] {
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ죄솧ㅇ해요

2022-11-28 02:31 UTC, seungki-cho commented on Acha/Acha/Domain/UseCase/DefaultRecordMainViewUseCase.swift
> +                    if let totalData = $0[dayString] {
간단한건 명시 안하는데 어려워져서 혼란스럽습니다

2022-11-28 02:31 UTC, seungki-cho commented on Acha/Acha/Presentation/TabBar/Record/RecordMap/RecordMapCategoryCell.swift
> +    }
코드만 보고 메서드 두개보단 변수 하나가 나을 것 같아서 적었습니다.만
직접접근보단 낫지않을까요?

2022-11-28 02:31 UTC, seungki-cho commented on Acha/Acha/Domain/UseCase/DefaultRecordMainViewUseCase.swift
> +            recordsAtDate[$0.createdAt] = recordsAtDate[$0.createdAt] ?? [] + [$0]
👍  누가 짰는 지아주 👍

2022-11-28 02:31 UTC, seungki-cho commented on Acha/Acha/Domain/UseCase/DefaultRecordMainViewUseCase.swift
> +        }
얼렁고쳐주세요

2022-11-28 02:31 UTC, seungki-cho commented on Acha/Acha/Domain/UseCase/DefaultRecordMapViewUseCase.swift
> +                    mapDataAtCategory[$0.location] = mapDataAtCategory[$0.location] ?? [] + [$0]
누짰아 👍

2022-11-29 12:57 UTC, sangyeon3 approved these changes

2022-11-29 12:57 UTC, sangyeon3 commented on Acha/Acha/Presentation/TabBar/Record/RecordMain/RecordMainViewController.swift
> +            case.chart:
`case .chart: ` 
case와 .chart 사이에 공백이 빠졌습니다

2022-11-29 12:57 UTC, sangyeon3 commented on Acha/Acha/Presentation/TabBar/Record/RecordMain/RecordMainViewController.swift
>  class RecordMainViewController: UIViewController, UICollectionViewDelegate {
final

2022-11-29 13:45 UTC, seungki-cho commented on Acha/Acha/Domain/UseCase/DefaultRecordMainViewUseCase.swift
> +                    recordsAtDate[$0.createdAt] = recordsAtDate[$0.createdAt] ?? [] + [$0]
갈호가 없습니다.

2022-11-29 15:14 UTC, seungki-cho approved these changes
수고하셧습니다
이 피알은 역사에 남을검니다

2022-11-29 15:14 UTC, seungki-cho commented on Acha/Acha/Presentation/TabBar/Record/RecordMain/RecordMainViewController.swift
> +
```cell.subviews.filter { $0 is LineGraphView }.forEach { $0.removeFromSuperview() }```

2022-11-29 15:18 UTC, sangyeon3 commented on Acha/Acha/Presentation/TabBar/Record/RecordMain/RecordMainChartCell.swift
> +    private lazy var fivethLabel = UILabel()
fifthLabel

2022-11-29 15:18 UTC, sangyeon3 commented on Acha/Acha/Presentation/TabBar/Record/RecordMain/RecordMainChartCell.swift
> +    private lazy var fivethDistanceLabel = UILabel()
fifthDistanceLabel

2022-11-29 15:43 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Record/RecordMain/LineGraphView.swift
> +        }
굳 아이디어!

2022-11-29 15:44 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Record/RecordMain/RecordMainChartCell.swift
> +        }
labelList 가 8개였던 시절의 흔적이 남아있군요 수정하겠습니다.

2022-11-29 15:44 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Record/RecordMain/RecordMainChartCell.swift
>              $0.top.bottom.leading.trailing.equalToSuperview()
넵!

2022-11-29 15:44 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Record/RecordMain/RecordMainViewController.swift
> +
와우 당신은 고차함수 고수!

2022-11-29 15:45 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Record/RecordMain/RecordMainCell.swift
> +    }
삭제하겠습니다!

2022-11-29 15:47 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Record/RecordMain/RecordMainChartCell.swift
> +    private lazy var largeStackView = UIStackView().then {
큰 스택뷰 안에 디스턴스 스택뷰와 백그라운드차트 스택뷰가 있습니다!

2022-11-29 15:47 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Record/RecordMain/RecordMainChartCell.swift
> +    private lazy var largeStackView = UIStackView().then {
배경으로 회색을 줘서 백그라운드차트 스택뷰의 스페이싱 만큼 회색줄이 보이게 해주려고했습니다.

2022-11-29 15:48 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Record/RecordMain/RecordMainChartCell.swift
> +    private lazy var fivethDistanceLabel = UILabel()
ㅎ... 승기님과 함께 웃으셨겠죠?

2022-11-29 15:48 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Record/RecordMain/RecordMainChartCell.swift
> +        print(#function)
sry..

2022-11-29 15:48 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Record/RecordMain/RecordMainChartCell.swift
>              let backgrounView = UIView().then {
감사합니다!

2022-11-29 15:49 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Record/RecordMain/RecordMainChartCell.swift
> +        }
좋습니다~

2022-11-29 15:49 UTC, NamSeok-Bae commented on Acha/Acha/Presentation/TabBar/Record/RecordMain/RecordMainChartCell.swift
> + */
어랏 저게 왜 저기 있죠?

2022-12-04 11:16 UTC, merged